controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    wheel_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


wheel_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController

    use_stamped_vel: false #To use Twist instead of TwistStamped
    
    left_wheel_names  : ['left_wheel_joint']
    right_wheel_names : ['right_wheel_joint']

    publish_rate: 50.0               # default: 50

    wheel_separation : 0.55
    wheel_radius : 0.15 #Its radius not dia. so r = dia/2 which is 0.12/2 = 0.06

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    # Velocity commands timeout [s], default 0.5
    cmd_vel_timeout: 0.5

    # Base frame_id
    base_frame_id: base_footprint #default: base_link

    # Publish limited velocity
    publish_limited_velocity: true

    # Publish wheel data
    publish_wheel_data: true

    # Publish to TF directly or not
    enable_odom_tf: true

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 1.0  # m/s
        min_velocity           : -1.0 # m/s
        has_acceleration_limits: true
        max_acceleration       : 1.0  # m/s^2
        min_acceleration       : -1.0 # m/s^2
        has_jerk_limits        : false
        max_jerk               : 0.5  # m/s^3
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 2.5  # rad/s
        min_velocity           : -2.5  # rad/s
        has_acceleration_limits: true
        max_acceleration       : 2.5  # rad/s^2
        min_acceleration       : -2.5   # rad/s^2
        has_jerk_limits        : false
        max_jerk               : 2.24  # rad/s^3

















